In [2]:
import numpy as np # linear algebra
import pandas as pd 
import matplotlib.pyplot as plt

interviews = pd.read_csv('Interview.csv')
interviews.head()

,Date of Interview,Client name,Industry,Location,Position to be closed,Nature of Skillset,Interview Type,Name(Cand ID),Gender,Candidate Current Location,...,Are you clear with the venue details and the landmark.,Has the call letter been shared,Expected Attendance,Observed Attendance,Marital Status,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 1,Male,Chennai,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 2,Male,Chennai,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 3,Male,Chennai,...,NaN,NaN,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 4,Male,Chennai,...,Yes,Yes,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 5,Male,Chennai,...,Yes,Yes,Uncertain,No,Married,NaN,NaN,NaN,NaN,NaN

In [3]:
#Original Column Names
interviews.columns

Index(['Date of Interview', 'Client name', 'Industry', 'Location',
       'Position to be closed', 'Nature of Skillset', 'Interview Type',
       'Name(Cand ID)', 'Gender', 'Candidate Current Location',
       'Candidate Job Location', 'Interview Venue',
       'Candidate Native location',
       'Have you obtained the necessary permission to start at the required time',
       'Hope there will be no unscheduled meetings',
       'Can I Call you three hours before the interview and follow up on your attendance for the interview',
       'Can I have an alternative number/ desk number. I assure you that I will not trouble you too much',
       'Have you taken a printout of your updated resume. Have you read the JD and understood the same',
       'Are you clear with the venue details and the landmark.',
       'Has the call letter been shared', 'Expected Attendance',
       'Observed Attendance', 'Marital Status', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27'],
      dtype='object')

In [4]:
interviews.tail()
interviews.drop(1233,inplace=True)

In [5]:
interviews

,Date of Interview,Client name,Industry,Location,Position to be closed,Nature of Skillset,Interview Type,Name(Cand ID),Gender,Candidate Current Location,...,Are you clear with the venue details and the landmark.,Has the call letter been shared,Expected Attendance,Observed Attendance,Marital Status,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 1,Male,Chennai,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 2,Male,Chennai,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 3,Male,Chennai,...,NaN,NaN,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 4,Male,Chennai,...,Yes,Yes,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Candidate 5,Male,Chennai,...,Yes,Yes,Uncertain,No,Married,NaN,NaN,NaN,NaN,NaN
5,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Candidate 6,Male,Gurgaon,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
6,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Candidate 7,Male,Gurgaon,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
7,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Candidate 8,Female,Gurgaon,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
8,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Candidate 9,Male,Gurgaon,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
9,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Candidate 10,Female,Gurgaon,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
10,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 11,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
11,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 12,Female,Bangalore,...,Yes,Yes,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
12,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 13,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
13,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 14,Male,Bangalore,...,Yes,Havent Checked,Uncertain,Yes,Single,NaN,NaN,NaN,NaN,NaN
14,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 15,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
15,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 16,Female,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
16,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 17,Female,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
17,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 18,Female,Bangalore,...,Yes,Yes,No,No,Single,NaN,NaN,NaN,NaN,NaN
18,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 19,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
19,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 20,Male,Bangalore,...,Yes,Yes,Yes,No,Single,NaN,NaN,NaN,NaN,NaN
20,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 21,Male,Bangalore,...,Yes,No,No,No,Single,NaN,NaN,NaN,NaN,NaN
21,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 22,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
22,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 23,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
23,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 24,Male,Bangalore,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
24,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 25,Male,Bangalore,...,Yes,Yes,Uncertain,No,Single,NaN,NaN,NaN,NaN,NaN
25,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 26,Male,Bangalore,...,Yes,No,No,No,Single,NaN,NaN,NaN,NaN,NaN
26,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 27,Male,Bangalore,...,Yes,No,No,No,Married,NaN,NaN,NaN,NaN,NaN
27,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Candidate 28,Male,Bangalore,...,Yes,No,No,No,Single,NaN,NaN,NaN,NaN,NaN
28,23.06.2015,Standard Chartered Bank,BFSI,Chennai,AML,Routine,Scheduled Walkin,Candidate 29,Female,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
29,23.06.2015,Standard Chartered Bank,BFSI,Chennai,AML,Routine,Scheduled Walkin,Candidate 30,Female,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,30.1.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1204,Male,Chennai,...,Yes,Yes,Yes,yes,Single,NaN,NaN,NaN,NaN,NaN
1204,30.1.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1205,Male,Chennai,...,Yes,Yes,Yes,yes,Single,NaN,NaN,NaN,NaN,NaN
1205,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1206,Female,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1206,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1207,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1207,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1208,Male,Chennai,...,Yes,Yes,Yes,No,Married,NaN,NaN,NaN,NaN,NaN
1208,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1209,Male,Chennai,...,Yes,Yes,Yes,yes,Married,NaN,NaN,NaN,NaN,NaN
1209,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1210,Male,Chennai,...,Yes,Yes,Yes,yes,Single,NaN,NaN,NaN,NaN,NaN
1210,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1211,Male,Chennai,...,Yes,Yes,Yes,yes,Married,NaN,NaN,NaN,NaN,NaN
1211,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1212,Male,Chennai,...,Yes,Yes,Yes,yes,Single,NaN,NaN,NaN,NaN,NaN
1212,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1213,Male,Chennai,...,Yes,Yes,Yes,no,Single,NaN,NaN,NaN,NaN,NaN
1213,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1214,Male,Chennai,...,Yes,Yes,Yes,no,Married,NaN,NaN,NaN,NaN,NaN
1214,30-1-2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1215,Female,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1215,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1216,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1216,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Candidate 1217,Male,Chennai,...,Yes,Yes,Yes,no,Single,NaN,NaN,NaN,NaN,NaN
1217,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Candidate 1218,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1218,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Candidate 1219,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1219,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Candidate 1220,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1220,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Candidate 1221,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1221,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Candidate 1222,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1222,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Candidate 1223,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1223,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Candidate 1224,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1224,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Candidate 1225,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1225,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,LCM -Manager,Scheduled,Candidate 1226,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1226,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Licensing â€“ RA,Scheduled,Candidate 1227,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1227,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Licensing â€“ RA,Scheduled,Candidate 1228,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1228,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Candidate 1229,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1229,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Candidate 1230,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1230,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Candidate 1231,Male,Chennai,...,Yes,Yes,Yes,Yes,Married,NaN,NaN,NaN,NaN,NaN
1231,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Candidate 1232,Male,Chennai,...,Yes,Yes,Yes,Yes,Single,NaN,NaN,NaN,NaN,NaN
1232,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Candidate 1233,Female,Chennai,...,NaN,NaN,Uncertain,Yes,Single,NaN,NaN,NaN,NaN,NaN

In [6]:
#dropping some unwanted columns
interviews.drop(['Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Name(Cand ID)'], 
                  axis=1, inplace=True)
interviews

,Date of Interview,Client name,Industry,Location,Position to be closed,Nature of Skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,Have you obtained the necessary permission to start at the required time,Hope there will be no unscheduled meetings,Can I Call you three hours before the interview and follow up on your attendance for the interview,Can I have an alternative number/ desk number. I assure you that I will not trouble you too much,Have you taken a printout of your updated resume. Have you read the JD and understood the same,Are you clear with the venue details and the landmark.,Has the call letter been shared,Expected Attendance,Observed Attendance,Marital Status
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Male,Chennai,Hosur,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Male,Chennai,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Male,Chennai,Chennai,...,NaN,Na,NaN,NaN,NaN,NaN,NaN,Uncertain,No,Single
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Male,Chennai,Chennai,...,Yes,Yes,No,Yes,No,Yes,Yes,Uncertain,No,Single
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walkin,Male,Chennai,Bangalore,...,Yes,Yes,Yes,No,Yes,Yes,Yes,Uncertain,No,Married
5,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Male,Gurgaon,Gurgaon,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
6,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Male,Gurgaon,Gurgaon,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
7,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Female,Gurgaon,Gurgaon,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
8,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Male,Gurgaon,Gurgaon,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
9,13.02.2015,Aon Hewitt,IT Services,Gurgaon,Selenium testing,Routine,Scheduled Walkin,Female,Gurgaon,Gurgaon,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
10,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
11,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Female,Bangalore,Bangalore,...,No,Yes,No,No,Yes,Yes,Yes,Uncertain,No,Single
12,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
13,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,No,Yes,Yes,Yes,Yes,Yes,Havent Checked,Uncertain,Yes,Single
14,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
15,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Female,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
16,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Female,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
17,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Female,Bangalore,Bangalore,...,No,Yes,Yes,No,Yes,Yes,Yes,No,No,Single
18,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
19,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
20,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Not yet,Yes,Yes,Yes,Yes,Yes,No,No,No,Single
21,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
22,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
23,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
24,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,Yes,Yes,Yes,No,No,Yes,Yes,Uncertain,No,Single
25,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,No,No,Yes,Yes,Yes,Yes,No,No,No,Single
26,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,No,Yes,Yes,Yes,Yes,Yes,No,No,No,Married
27,19.06.2015,UST,IT Services,Bangalore,Dot Net,Routine,Scheduled Walkin,Male,Bangalore,Bangalore,...,No,Yes,Yes,Yes,No,Yes,No,No,No,Single
28,23.06.2015,Standard Chartered Bank,BFSI,Chennai,AML,Routine,Scheduled Walkin,Female,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
29,23.06.2015,Standard Chartered Bank,BFSI,Chennai,AML,Routine,Scheduled Walkin,Female,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,30.1.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Single
1204,30.1.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Single
1205,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Female,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1206,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1207,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Married
1208,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Married
1209,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Single
1210,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Married
1211,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,yes,Single
1212,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,no,Single
1213,30.01.16,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,no,Married
1214,30-1-2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Female,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1215,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1216,30.01.2016,Standard Chartered Bank,BFSI,Chennai,Routine,Java,Scheduled Walk In,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,no,Single
1217,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1218,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1219,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1220,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,RA Publishing,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1221,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1222,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1223,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,EMEA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1224,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1225,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,LCM -Manager,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1226,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Licensing â€“ RA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1227,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Licensing â€“ RA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1228,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1229,07.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1230,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,Biosimiliars,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Married
1231,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Male,Chennai,Chennai,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Single
1232,06.05.2016,Pfizer,Pharmaceuticals,Chennai,Niche,generic drugs â€“ RA,Scheduled,Female,Chennai,Chennai,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uncertain,Yes,Single

In [7]:
newnames = {
    'Have you obtained the necessary permission to start at the required time':'necessary_permission',
    'Hope there will be no unscheduled meetings':'unscheduled_meetings',
    'Can I Call you three hours before the interview and follow up on your attendance for the interview':'followup_3hours_call',
    'Can I have an alternative number/ desk number. I assure you that I will not trouble you too much':'alternative_number',
    'Have you taken a printout of your updated resume. Have you read the JD and understood the same':'resume_printout_JD',
    'Are you clear with the venue details and the landmark.':'venue_details',
    'Has the call letter been shared':'shared_call_letter',
    'Nature of Skillset':'skillset',
    'Position to be closed':'position'
}
interviews.rename(columns=newnames, inplace=True)

In [8]:
#New simplified column names
interviews.columns

Index(['Date of Interview', 'Client name', 'Industry', 'Location', 'position',
       'skillset', 'Interview Type', 'Gender', 'Candidate Current Location',
       'Candidate Job Location', 'Interview Venue',
       'Candidate Native location', 'necessary_permission',
       'unscheduled_meetings', 'followup_3hours_call', 'alternative_number',
       'resume_printout_JD', 'venue_details', 'shared_call_letter',
       'Expected Attendance', 'Observed Attendance', 'Marital Status'],
      dtype='object')

In [9]:
#Now cleaning up range of responses in individual fields
interviews.loc[interviews['Observed Attendance']=='NO','Observed Attendance']='No'
interviews.loc[interviews['Observed Attendance']=='No ','Observed Attendance']='No'
interviews.loc[interviews['Observed Attendance']=='no ','Observed Attendance']='No'
interviews.loc[interviews['Observed Attendance']=='no','Observed Attendance']='No'
interviews['Observed Attendance'].value_counts()

Yes     701
No      450
yes      81
yes       1
Name: Observed Attendance, dtype: int64

In [10]:
interviews.loc[interviews['Observed Attendance']=='yes','Observed Attendance']='Yes'
interviews['Observed Attendance'].value_counts()

Yes     782
No      450
yes       1
Name: Observed Attendance, dtype: int64

In [11]:
#confirmed you have to run the previous two lines twice to remove the lowercase 'yes' response
interviews.loc[interviews['Observed Attendance']=='yes ','Observed Attendance']='Yes'
interviews['Observed Attendance'].value_counts()

Yes    783
No     450
Name: Observed Attendance, dtype: int64

In [12]:
interviews['Expected Attendance'].value_counts()
interviews.loc[interviews['Expected Attendance']=='No ','Expected Attendance']='No'
interviews.loc[interviews['Expected Attendance']=='NO','Expected Attendance']='No'
interviews.loc[interviews['Expected Attendance']=='Uncertain','Expected Attendance']='No'
interviews.loc[interviews['Expected Attendance']=='yes','Expected Attendance']='Yes'
interviews['Expected Attendance'].value_counts()

Yes         883
No          343
11:00 AM      1
10.30 Am      1
Name: Expected Attendance, dtype: int64

In [13]:
interviews.loc[interviews['Expected Attendance']=='11:00 AM','Expected Attendance']='Yes'
interviews.loc[interviews['Expected Attendance']=='10.30 Am','Expected Attendance']='Yes'

In [14]:
interviews['Expected Attendance'].value_counts()

Yes    885
No     343
Name: Expected Attendance, dtype: int64

In [15]:
interviews['Interview Type'].value_counts()

Scheduled Walk In    456
Scheduled            371
Walkin               189
Scheduled Walkin     189
Walkin                27
Sceduled walkin        1
Name: Interview Type, dtype: int64

In [16]:
#changing code to leave 3 interview types:Scheduled, Walk In, and Scheduled Walk In
interviews.loc[interviews['Interview Type']=='Scheduled Walkin','Interview Type']='Scheduled Walk-In'
interviews.loc[interviews['Interview Type']=='Sceduled walkin','Interview Type']='Scheduled Walk-In'
interviews.loc[interviews['Interview Type']=='Scheduled Walk In','Interview Type']='Scheduled Walk-In'
interviews.loc[interviews['Interview Type']=='Walkin ','Interview Type']='Walk-In'
interviews.loc[interviews['Interview Type']=='Walkin','Interview Type']='Walk-In'
interviews['Interview Type'].value_counts()

Scheduled Walk-In    646
Scheduled            371
Walk-In              216
Name: Interview Type, dtype: int64

In [17]:
interviews['shared_call_letter'].value_counts()

Yes               932
Na                 19
No                 17
Not Sure            8
Need To Check       3
Not yet             2
yes                 2
Not sure            1
Yet to Check        1
no                  1
Havent Checked      1
na                  1
Name: shared_call_letter, dtype: int64

In [18]:
#multiple blocks like this one didn't work because of double equal sign. So I guess it was comparing them, instead of assigning
interviews.loc[interviews['shared_call_letter']=='yes','shared_call_letter']=='Yes'
interviews.loc[interviews['shared_call_letter']=='Na','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='Not Sure','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='Need To Check','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='Not yet','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='Yet to Check','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='na','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='Havent Checked','shared_call_letter']=='No'
interviews.loc[interviews['shared_call_letter']=='no','shared_call_letter']=='No'
interviews['shared_call_letter'].value_counts()

Yes               932
Na                 19
No                 17
Not Sure            8
Need To Check       3
Not yet             2
yes                 2
Not sure            1
Yet to Check        1
no                  1
Havent Checked      1
na                  1
Name: shared_call_letter, dtype: int64

In [19]:
interviews.loc[interviews['shared_call_letter']=='yes','shared_call_letter']='Yes'
interviews.loc[interviews['shared_call_letter']=='Na','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Not yet','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Not Sure','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Need To Check','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Yet to Check','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Havent Checked','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='no','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='na','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='Not sure','shared_call_letter']='No/Need to Check'
interviews.loc[interviews['shared_call_letter']=='No','shared_call_letter'] = 'No/Need to Check'

In [20]:
interviews['shared_call_letter'].value_counts()

Yes                 934
No/Need to Check     54
Name: shared_call_letter, dtype: int64

In [21]:
interviews.head()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Observed Attendance,Marital Status
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Hosur,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,NaN,Na,NaN,NaN,NaN,NaN,NaN,No,No,Single
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Single
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,Married

In [22]:
interviews['venue_details'].value_counts()

Yes                    946
Na                      19
No                      14
yes                      2
No- I need to check      2
no                       1
na                       1
Name: venue_details, dtype: int64

In [23]:
interviews.loc[interviews['venue_details']=='yes','venue_details']='Yes'
interviews.loc[interviews['venue_details']=='Na','venue_details']='No'
interviews.loc[interviews['venue_details']=='No- I need to check','venue_details']='No'
interviews.loc[interviews['venue_details']=='no','venue_details']='No'
interviews.loc[interviews['venue_details']=='na','venue_details']='No'

In [24]:
interviews['venue_details'].value_counts()

Yes    948
No      37
Name: venue_details, dtype: int64

In [25]:
interviews['resume_printout_JD'].value_counts()

Yes                      940
Na                        19
No                        16
Not Yet                    4
Not yet                    2
yes                        2
No- will take it soon      1
na                         1
Name: resume_printout_JD, dtype: int64

In [26]:
interviews.loc[interviews['resume_printout_JD']=='yes','resume_printout_JD']='Yes'
interviews.loc[interviews['resume_printout_JD']=='Na','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='No- Will take it soon','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='No','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='Not yet','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='Not Yet','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='na','resume_printout_JD']='No'
interviews.loc[interviews['resume_printout_JD']=='No- will take it soon','resume_printout_JD']='No'

In [27]:
interviews['resume_printout_JD'].value_counts()

Yes    942
No      43
Name: resume_printout_JD, dtype: int64

In [28]:
interviews['alternative_number'].value_counts()

Yes                          936
No                            27
Na                            19
No I have only thi number      2
yes                            1
na                             1
Name: alternative_number, dtype: int64

In [29]:
interviews.loc[interviews['alternative_number']=='yes','alternative_number']='Yes'
interviews.loc[interviews['alternative_number']=='Na','alternative_number']='No'
interviews.loc[interviews['alternative_number']=='No- I have only thi number','alternative_number']='No'
interviews.loc[interviews['alternative_number']=='No','alternative_number']='No'
interviews.loc[interviews['alternative_number']=='na','alternative_number']='No'
interviews.loc[interviews['alternative_number']=='No I have only thi number','alternative_number']='No'

In [30]:
interviews['alternative_number'].value_counts()

Yes    937
No      49
Name: alternative_number, dtype: int64

In [31]:
interviews['followup_3hours_call'].value_counts()

Yes        951
Na          20
No          10
yes          4
No Dont      1
Name: followup_3hours_call, dtype: int64

In [32]:
interviews.loc[interviews['followup_3hours_call']=='yes','followup_3hours_call']='Yes'
interviews.loc[interviews['followup_3hours_call']=='Na','followup_3hours_call']='No'
interviews.loc[interviews['followup_3hours_call']=='No Dont','followup_3hours_call']='No'
interviews.loc[interviews['followup_3hours_call']=='No','followup_3hours_call']='No'

In [33]:
interviews['followup_3hours_call'].value_counts()

Yes    955
No      31
Name: followup_3hours_call, dtype: int64

In [34]:
interviews['unscheduled_meetings'].value_counts()

Yes         949
Na           20
No            6
yes           5
Not sure      4
cant Say      1
Not Sure      1
Name: unscheduled_meetings, dtype: int64

In [35]:
interviews.loc[interviews['unscheduled_meetings']=='yes','unscheduled_meetings']='Yes'
interviews.loc[interviews['unscheduled_meetings']=='Na','unscheduled_meetings']='No'
interviews.loc[interviews['unscheduled_meetings']=='Not Sure','unscheduled_meetings']='No'
interviews.loc[interviews['unscheduled_meetings']=='Not sure','unscheduled_meetings']='No'
interviews.loc[interviews['unscheduled_meetings']=='cant say','unscheduled_meetings']='No'

In [36]:
interviews.loc[interviews['unscheduled_meetings']=='cant Say','unscheduled_meetings']='No'

In [37]:
interviews['unscheduled_meetings'].value_counts()

Yes    954
No      32
Name: unscheduled_meetings, dtype: int64

In [38]:
interviews['necessary_permission'].value_counts()

Yes               917
No                 79
Not yet            19
Na                  5
yes                 4
Yet to confirm      4
NO                  1
Name: necessary_permission, dtype: int64

In [39]:
interviews.loc[interviews['necessary_permission']=='yes','necessary_permission']='Yes'
interviews.loc[interviews['necessary_permission']=='Na','necessary_permission']='No'
interviews.loc[interviews['necessary_permission']=='Not yet','necessary_permission']='No'
interviews.loc[interviews['necessary_permission']=='Yet to confirm','necessary_permission']='No'
interviews.loc[interviews['necessary_permission']=='NO','necessary_permission']='No'

In [40]:
interviews['necessary_permission'].value_counts()

Yes    921
No     108
Name: necessary_permission, dtype: int64

In [41]:
interviews.head()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Observed Attendance,Marital Status
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Hosur,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,NaN,No,NaN,NaN,NaN,NaN,NaN,No,No,Single
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Single
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Production- Sterile,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,Married

In [42]:
interviews['Candidate Job Location'].value_counts()

Chennai          893
Bangalore        259
Gurgaon           35
Visakapatinam     21
Noida             15
- Cochin-          9
Hosur              1
Name: Candidate Job Location, dtype: int64

In [43]:
interviews['Candidate Current Location'].value_counts()

Chennai       754
Bangalore     292
chennai        86
Hyderabad      38
Gurgaon        34
Noida          15
- Cochin-       9
chennai         3
Delhi           1
CHENNAI         1
Name: Candidate Current Location, dtype: int64

In [44]:
interviews.loc[interviews['Candidate Current Location']=='chennai','Candidate Current Location']='Chennai'
interviews.loc[interviews['Candidate Current Location']=='CHENNAI','Candidate Current Location']='Chennai'
interviews.loc[interviews['Candidate Current Location']=='chennai ','Candidate Current Location']='Chennai'

In [45]:
interviews['Candidate Current Location'].value_counts()

Chennai       844
Bangalore     292
Hyderabad      38
Gurgaon        34
Noida          15
- Cochin-       9
Delhi           1
Name: Candidate Current Location, dtype: int64

In [46]:
interviews['Location'].value_counts()

Chennai       754
Bangalore     292
chennai        86
Hyderabad      38
Gurgaon        33
Noida          15
- Cochin-       9
chennai         3
Gurgaonr        1
Delhi           1
CHENNAI         1
Name: Location, dtype: int64

In [47]:
interviews.loc[interviews['Location']=='chennai','Location']='Chennai'
interviews.loc[interviews['Location']=='CHENNAI','Location']='Chennai'
interviews.loc[interviews['Location']=='chennai ','Location']='Chennai'
interviews.loc[interviews['Location']=='Gurgaonr ','Location']='Gurgaon'

In [48]:
interviews['Location'].value_counts()

Chennai       844
Bangalore     292
Hyderabad      38
Gurgaon        33
Noida          15
- Cochin-       9
Gurgaonr        1
Delhi           1
Name: Location, dtype: int64

In [49]:
interviews.loc[interviews['Location']=='Gurgaonr','Location']='Gurgaon'

In [50]:
interviews['Location'].value_counts()

Chennai       844
Bangalore     292
Hyderabad      38
Gurgaon        34
Noida          15
- Cochin-       9
Delhi           1
Name: Location, dtype: int64

In [51]:
interviews['skillset'].value_counts()
#way to messy to deal with. Don't think we should delete it, but don't think it'll be included in the models

JAVA/J2EE/Struts/Hibernate                220
Fresher                                    86
Accounting Operations                      86
AML/KYC/CDD                                84
CDD KYC                                    52
Routine                                    47
Oracle                                     43
JAVA/SPRING/HIBERNATE/JSF                  42
Java J2EE                                  33
SAS                                        27
Oracle Plsql                               25
Java Developer                             25
Banking Operations                         22
Lending and Liabilities                    22
Java                                       21
Core Java                                  17
Java J2ee                                  16
ALS Testing                                15
T-24 developer                             15
Senior software engineer-Mednet            15
SCCM                                       14
COTS Developer                             13
Analytical R & D                           13
Sr Automation Testing                      13
Hadoop                                     12
Regulatory                                 12
testing                                    11
Java                                       10
ETL                                         9
RA Publishing                               9
                                         ...
Java, SQL                                   3
Java,SQL                                    3
Lending&Liablities                          2
11.30 AM                                    2
Banking operations                          2
LCM -Manager                                2
Production Support - SCCM                   2
L & L                                       2
Submission Management                       2
Java, Spring, Hibernate                     2
RA Label                                    2
JAVA, J2ee                                  1
SCCM â€“ Sharepoint                           1
Manager                                     1
12.30 Pm                                    1
sccm                                        1
SCCM â€“ SQL                                  1
11.30 Am                                    1
BaseSAS Program/ Reporting                  1
Tech Lead- Mednet                           1
Technical Lead                              1
Biosimilars                                 1
9.00 Am                                     1
Sccm- networking                            1
JAVA,J2ee                                   1
10.00 AM                                    1
Production                                  1
SCCM-(Network, sharepoint,ms exchange)      1
Java, J2Ee                                  1
9.30 AM                                     1
Name: skillset, Length: 92, dtype: int64

In [52]:
interviews['position'].value_counts()

Routine                1023
Niche                   163
Dot Net                  18
Trade Finance            11
AML                       8
Selenium testing          5
Production- Sterile       5
Name: position, dtype: int64

In [53]:
#Simplifying position to Routine vs Niche
interviews.loc[interviews['position']=='Dot Net','position']='Niche'
interviews.loc[interviews['position']=='Trade Finance','position']='Niche'
interviews.loc[interviews['position']=='AML','position']='Niche'
interviews.loc[interviews['position']=='Selenium testing','position']='Niche'
interviews.loc[interviews['position']=='Production- Sterile','position']='Niche'

In [54]:
interviews['position'].value_counts()

Routine    1023
Niche       210
Name: position, dtype: int64

In [55]:
#writing our cleaned dataset to csv
type(interviews)

pandas.core.frame.DataFrame

In [71]:
#removed indexes from left side of each row
interviews.to_csv('CleanedInterviews-FINAL.csv', encoding='utf-8', index=False)

In [57]:
from sklearn import datasets, linear_model
from sklearn.metrics import accuracy_score 
import pandas as pd 
import numpy as np
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import statsmodels.api as sm

interviews = interviews.dropna()

interviews = interviews.apply(LabelEncoder().fit_transform)
from sklearn.linear_model import LogisticRegression
Y_train=interviews['Observed Attendance']

del interviews['Observed Attendance']

X_train = interviews
interviews.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.35, random_state=42)
#print (X_train.shape, y_train.shape)
#print (X_test.shape, y_test.shape)
#print(X_test)

############################################################

#Random Forest implementation

############################################################

from sklearn.ensemble import RandomForestClassifier
randomf = RandomForestClassifier(n_jobs=2, random_state=0)
randomf.fit(X_train,y_train)
score = randomf.score(X_test, y_test)
prediction_randomForest = randomf.predict(X_test)
prediction_randomForest_train=randomf.predict(X_train)
print('Train/Test split results:')
print(" Random Forest score is %2.3f" % accuracy_score(y_train, prediction_randomForest_train))

############################################################

# Logistic Regression implementation

############################################################
lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
predictions = lm.predict(X_test)
log=LogisticRegression()
result  = log.fit(X_train,y_train)
score = log.score(X_test, y_test)
print("Logistic Regression Score %2.3f" % score)

C:\Users\Praveen\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

Train/Test split results:
 Random Forest score is 0.854
Logistic Regression Score 0.739

In [58]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import train_test_split, cross_val_score
df = pd.read_csv('CleanedInterviews-FINAL.csv')
print(len(df)) #total number of rows

1233

In [59]:
#Using label encoder to label variables
label = LabelEncoder()
#selecting the subset of our dataset to be features in DT. 
cols = df.columns
print(cols)
print(type(cols))

#Choosing specific columns. Starting with the easy ones first
chosenFeatures = ['Client name', 'Industry', 'Location', 'position',
        'Interview Type', 'Gender', 'necessary_permission',
       'unscheduled_meetings', 'followup_3hours_call', 'alternative_number',
       'resume_printout_JD', 'venue_details', 'shared_call_letter',
       'Expected Attendance', 'Marital Status']

Index(['Date of Interview', 'Client name', 'Industry', 'Location', 'position',
       'skillset', 'Interview Type', 'Gender', 'Candidate Current Location',
       'Candidate Job Location', 'Interview Venue',
       'Candidate Native location', 'necessary_permission',
       'unscheduled_meetings', 'followup_3hours_call', 'alternative_number',
       'resume_printout_JD', 'venue_details', 'shared_call_letter',
       'Expected Attendance', 'Observed Attendance', 'Marital Status'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [60]:
#need to convert to list, because we can converst list to integers
#cols = chosenColumns.tolist()
#initializing new empty Pandas DataFrame
indepVars = pd.DataFrame()

#Interating over our list to append columns to new DataFrame
for column in chosenFeatures:
    #print(column)
    #doing a transformation for each column in cols to convert from type 'object' to 'string'
    indepVars[column] = label.fit_transform(df[column].astype('str'))
    
print(indepVars.head(5))

   Client name  Industry  Location  position  Interview Type  Gender  \
0            7         5         2         0               1       1
1            7         5         2         0               1       1
2            7         5         2         0               1       1
3            7         5         2         0               1       1
4            7         5         2         0               1       1

   necessary_permission  unscheduled_meetings  followup_3hours_call  \
0                     1                     1                     1
1                     1                     1                     1
2                     2                     0                     2
3                     1                     1                     0
4                     1                     1                     1

   alternative_number  resume_printout_JD  venue_details  shared_call_letter  \
0                   1                   1              1                   1
1                   1                   1              1                   1
2                   2                   2              2                   2
3                   1                   0              1                   1
4                   0                   1              1                   1

   Expected Attendance  Marital Status
0                    1               1
1                    1               1
2                    0               1
3                    0               1
4                    0               0

In [61]:
#First creating dependent and independent variables as own objects
depVar = pd.DataFrame()
for column in ['Observed Attendance']:
    #print(column)
    #doing a transformation for each column in cols to convert from type 'object' to 'string'
    depVar[column] = label.fit_transform(df[column].astype('str'))
Y = depVar
X = indepVars
print(X.head(5))
print(Y.head(5))

   Client name  Industry  Location  position  Interview Type  Gender  \
0            7         5         2         0               1       1
1            7         5         2         0               1       1
2            7         5         2         0               1       1
3            7         5         2         0               1       1
4            7         5         2         0               1       1

   necessary_permission  unscheduled_meetings  followup_3hours_call  \
0                     1                     1                     1
1                     1                     1                     1
2                     2                     0                     2
3                     1                     1                     0
4                     1                     1                     1

   alternative_number  resume_printout_JD  venue_details  shared_call_letter  \
0                   1                   1              1                   1
1                   1                   1              1                   1
2                   2                   2              2                   2
3                   1                   0              1                   1
4                   0                   1              1                   1

   Expected Attendance  Marital Status
0                    1               1
1                    1               1
2                    0               1
3                    0               1
4                    0               0
   Observed Attendance
0                    0
1                    0
2                    0
3                    0
4                    0

In [62]:
#Seeing if each column has the expected number of levels (to account for NAs)
for col in chosenFeatures:
    print(indepVars[col].value_counts())

10    904
8      75
7      75
1      28
5      23
0      22
6      20
12     18
11     17
9      17
3      15
13     11
4       5
2       2
14      1
Name: Client name, dtype: int64
0    949
5    165
3     45
4     23
1     23
6     17
2     11
Name: Industry, dtype: int64
2    844
1    292
5     38
4     34
6     15
0      9
3      1
Name: Location, dtype: int64
1    1023
0     210
Name: position, dtype: int64
1    646
0    371
2    216
Name: Interview Type, dtype: int64
1    965
0    268
Name: Gender, dtype: int64
1    921
2    204
0    108
Name: necessary_permission, dtype: int64
1    954
2    247
0     32
Name: unscheduled_meetings, dtype: int64
1    955
2    247
0     31
Name: followup_3hours_call, dtype: int64
1    937
2    247
0     49
Name: alternative_number, dtype: int64
1    942
2    248
0     43
Name: resume_printout_JD, dtype: int64
1    948
2    248
0     37
Name: venue_details, dtype: int64
1    934
2    245
0     54
Name: shared_call_letter, dtype: int64
1    885
0    343
2      5
Name: Expected Attendance, dtype: int64
1    767
0    466
Name: Marital Status, dtype: int64

In [63]:
#now comparing to value_counts of original columns
for col in chosenFeatures:
    print(df[col].value_counts())

Standard Chartered Bank            904
Hospira                             75
Pfizer                              75
Aon Hewitt                          28
Flextronics                         23
ANZ                                 22
Hewitt                              20
UST                                 18
Prodapt                             17
Standard Chartered Bank Chennai     17
Astrazeneca                         15
Williams Lea                        11
Barclays                             5
Aon hewitt Gurgaon                   2
Woori Bank                           1
Name: Client name, dtype: int64
BFSI                        949
Pharmaceuticals             165
IT Products and Services     45
Electronics                  23
IT Services                  23
Telecom                      17
IT                           11
Name: Industry, dtype: int64
Chennai       844
Bangalore     292
Hyderabad      38
Gurgaon        34
Noida          15
- Cochin-       9
Delhi           1
Name: Location, dtype: int64
Routine    1023
Niche       210
Name: position, dtype: int64
Scheduled Walk-In    646
Scheduled            371
Walk-In              216
Name: Interview Type, dtype: int64
Male      965
Female    268
Name: Gender, dtype: int64
Yes    921
No     108
Name: necessary_permission, dtype: int64
Yes    954
No      32
Name: unscheduled_meetings, dtype: int64
Yes    955
No      31
Name: followup_3hours_call, dtype: int64
Yes    937
No      49
Name: alternative_number, dtype: int64
Yes    942
No      43
Name: resume_printout_JD, dtype: int64
Yes    948
No      37
Name: venue_details, dtype: int64
Yes                 934
No/Need to Check     54
Name: shared_call_letter, dtype: int64
Yes    885
No     343
Name: Expected Attendance, dtype: int64
Single     767
Married    466
Name: Marital Status, dtype: int64

In [64]:
#Dropping NAs from original df and rerunning the labelEncoding
noMissing = df.dropna()
print(len(noMissing))
indepVars = pd.DataFrame()

#Interating over our list to append columns to new DataFrame
for column in chosenFeatures:
    #print(column)
    #doing a transformation for each column in cols to convert from type 'object' to 'string'
    indepVars[column] = label.fit_transform(noMissing[column].astype('str'))
    

depVar = pd.DataFrame()
for column in ['Observed Attendance']:
    #print(column)
    #doing a transformation for each column in cols to convert from type 'object' to 'string'
    depVar[column] = label.fit_transform(noMissing[column].astype('str'))
Y = depVar
X = indepVars

984

In [65]:
##Splitting the data into training and testing sets##
#print(len(train_test_split(X,Y,))) #will take data and sample proportion as 33% as test and 66% training
#returns 4 because of 4 parts: split X and Y into 2 each

X_train, X_test,Y_train,Y_test = train_test_split(X,Y)
##Building the Decision Tree##
from sklearn.metrics import accuracy_score

#ensure we get consistent results across runs
np.random.seed(4242)


decision_clf = DecisionTreeClassifier(max_depth=5)
decision_clf = decision_clf.fit(X_train, Y_train)

#Give data to classifier so it can generate model. Test with our test data

decision_predict = decision_clf.predict(X_test)

print(accuracy_score(Y_test,decision_predict))

0.776422764228

In [66]:
#10-fold cross validation
decision_clf2 = DecisionTreeClassifier(max_depth = 5) #will different values for 'max_depth = ' as arg in DecisionTreeClassifier
decision_clf2 = decision_clf2.fit(X_train, Y_train)

cross_val_score(decision_clf2,X_train,Y_train,cv=10)

array([ 0.69333333,  0.74666667,  0.68      ,  0.67567568,  0.71621622,
        0.76712329,  0.73972603,  0.73972603,  0.73972603,  0.7260274 ])

In [67]:
import os
import subprocess
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

In [74]:
visualize_tree(decision_clf, chosenFeatures)

Visualization of Decision Tree. **Make sure graphviz is installed in your system.**

If not, use the below code on console:

Conda install python-graphiz

Conda install graphviz

In [69]:
print(os.path)
from graphviz import Digraph
from sklearn.tree import export_graphviz
import graphviz
from sklearn.tree import export_graphviz
import graphviz

export_graphviz(decision_clf, out_file="mytree.dot")
with open("mytree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

<module 'ntpath' from 'C:\\Users\\Praveen\\Anaconda3\\lib\\ntpath.py'>

ModuleNotFoundError: No module named 'graphviz'

In [72]:
from sklearn import tree
dotfile = open("D:/dtreeFINAL.dot", 'w')
dot_data = tree.export_graphviz(decision_clf, out_file=dotfile, feature_names=list(chosenFeatures), class_names=["Absent", "Non-Absent"])
graph = graphviz.Source(dot_data)  
graph
dotfile.close()

NameError: name 'graphviz' is not defined